// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpClientMock is an autogenerated mock type for the HttpClient type
type HttpClientMock struct {
	mock.Mock
}

// Post provides a mock function with given fields: url, body, headers
func (_m *HttpClientMock) Post(url string, body interface{}, headers map[string]string) ([]byte, error) {
	ret := _m.Called(url, body, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, interface{}, map[string]string) []byte); ok {
		r0 = rf(url, body, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, map[string]string) error); ok {
		r1 = rf(url, body, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
