// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoggerMock is an autogenerated mock type for the Logger type
type LoggerMock struct {
	mock.Mock
}

// Debug provides a mock function with given fields: format, content
func (_m *LoggerMock) Debug(format string, content ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, content...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: format, content
func (_m *LoggerMock) Error(format string, content ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, content...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: format, content
func (_m *LoggerMock) Fatal(format string, content ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, content...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: format, content
func (_m *LoggerMock) Info(format string, content ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, content...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: format, content
func (_m *LoggerMock) Warn(format string, content ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, content...)
	_m.Called(_ca...)
}
