// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment "github.com/facilittei/ecomm/internal/domains/payment"
	mock "github.com/stretchr/testify/mock"
)

// PaymentServiceMock is an autogenerated mock type for the Payment type
type PaymentServiceMock struct {
	mock.Mock
}

// Charge provides a mock function with given fields: req
func (_m *PaymentServiceMock) Charge(req payment.Request) (map[string]string, error) {
	ret := _m.Called(req)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(payment.Request) map[string]string); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(payment.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
