package payment

import (
	"github.com/facilittei/ecomm/internal/domains/customer"
	"github.com/google/uuid"
)

// Request receives a payment intention for buying a product
// with all necessary information: customer, address, product and payment method
type Request struct {
	Description string            `json:"description"`
	Amount      float64           `json:"amount"`
	Customer    customer.Customer `json:"customer"`
	CreditCard  CreditCard        `json:"creditCard"`
}

// CreditCard holds credit card hash generated by payment provider
type CreditCard struct {
	Hash string `json:"hash"`
}

// Charge holds payment charges
type Charge struct {
	ID       uuid.UUID         `json:"id"`
	SKU      string            `json:"sku"`
	Customer customer.Customer `json:"customer"`
	History  []ChargeHistory   `json:"history"`
}

// ChargeHistory holds payment charge states
type ChargeHistory struct {
	Status      string `json:"status"`
	Description string `json:"description"`
}
